# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: csauron <csauron@students.42.fr>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/17 07:33:51 by csauron           #+#    #+#              #
#    Updated: 2024/10/17 07:33:53 by csauron          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


CC = gcc
CFLAGS = -Wall -Wextra -Iinclude

all: bruteforce

bruteforce: src/bruteforce.c
	$(CC) $(CFLAGS) -o bruteforce src/bruteforce.c

clean:
	rm -f bruteforce
